### ISSUE TITLE
Install Instructions Do Not Work

### ISSUE THREAD

**Issue by OR13** [serverless/site#110]
I'm trying to get this site to build locally, I found it from phenomic.

on npm install, I'm seeing:

```
Installing external content
--------------------------
No serverless blog repo found. Clone it from github
--------------------------
Cloning repo down master branch of git@github.com:serverless/blog.git to ./serverless-blog
No serverless docs repo found. Clone it from github
--------------------------
NOTE: serverless docs repo is big. Might take a minute to download
--------------------------
Cloning repo down master branch of git@github.com:serverless/serverless.git to ./serverless
Cloning into 'serverless-blog'...

Cloning into 'serverless'...
```

Then getting rejected for lack of access to these repos, and obviously `npm run start` does not work without them.

I'm a little surprised your static website has these as dependencies.

The reason, I'm trying to build your static website, is... it rocks!

And I'm working on an ethereum smart contract framework which needs a better cloud functions backend. So far, I've only toyed with firebase functions, which are more restrictive than serverless. 

I was hoping that by building your site I might learn more about how a serverless integration would look, while also learning whether or not this style static site is appropriate for our framework.

**Comment by DavidWells** [comment]
@OR13 I've updated the install process to account for non ssh github users.

If you clone this down again and `npm install` it should work for you.

In terms of serverless functions you will want to check out https://github.com/serverless/examples for service examples you can deploy to AWS/Azure/Etc

**Comment by OR13** [comment]
@DavidWells thanks for your reply, I'll check it out.
