### ISSUE TITLE
Homepage demo not working

### ISSUE THREAD

**Issue by fernando-mc** [serverless/site#122]
![screen shot 2017-07-24 at 10 49 19 pm](https://user-images.githubusercontent.com/6182464/28557633-6cf5dfb0-70c2-11e7-99eb-90b32e0e4bfc.png)

<img width="675" alt="img 2" src="https://user-images.githubusercontent.com/6182464/28557631-69b0e6e2-70c2-11e7-9b0a-1b14567c1ecf.png">

Did I do something incorrectly or is the suggested example from the homepage broken?

I think this is because the templates were changed in a previous version. The documentation has a different recommendation for quickstart commands: https://serverless.com/framework/docs/providers/aws/guide/quick-start/

I opened a PR for a possible fix. https://github.com/serverless/site/pull/121

**Comment by fernando-mc** [comment]
@DavidWells Seems like a pretty straightforward issue, not sure who to ping on this.

**Comment by DavidWells** [comment]
Hey @fernando-mc thanks for the heads up. 

cc @pmuens did the framework remove hello world template?

**Comment by DavidWells** [comment]
I'm unable to recreate this issue 

![image](https://user-images.githubusercontent.com/532272/29144969-dbec1b7e-7d0f-11e7-9eb0-206e28540613.png)

What version of the framework are you using @fernando-mc ?

**Comment by fernando-mc** [comment]
Upgrading solved the issue. Hadn't realized my version was so old.  Closing this and the open pr for the fix.

**Comment by pmuens** [comment]
Thanks for opening @fernando-mc and thanks for resolving @DavidWells 👍

Should we maybe remove the `version 1.0` in the graphics on the left? Or replace it with `version 1`? Right now it looks like the commands on the left work with Serverless `v1.0` or earlier.
