### ISSUE TITLE
Website rebrand: Event Gateway

### ISSUE THREAD

**Issue by jfdesroches** [serverless/site#131]
**Content**
[Google doc](https://docs.google.com/document/d/1B9teQNgf5qQ8ZB14xV_z8JtnT0jMRIVKXpCcBA7hCWY/edit#) 
- [ ] Content signoff (Andrea Passwater)

**UI to dos & fixes**
- [x] navigation Serverless icon should be white on colored backgrounds
- [x] add "View Github" button that links out to the Gateway repo
<img width="588" alt="screen shot 2017-08-14 at 4 55 13 pm" src="https://user-images.githubusercontent.com/5177299/29296776-5d9032c8-8111-11e7-8ec0-84061a0000eb.png">

- [x] background ghost image for hero/header (Felix to provide by 8/15)
- [x] bump down the features mini text block font to 300 weight (same edit as to the Framework page):
![screen shot 2017-08-14 at 3 31 03 pm](https://user-images.githubusercontent.com/5177299/29294743-c72a2b78-8105-11e7-9e10-7006ea2211e6.png)

**Animations and states**
- [ ] same as components on other pages

CC @steelbrain @andrea-p @worldsoup

**Comment by jfdesroches** [comment]
- [ ] let's remove the intro text block and the Serverless dotted line slash, so it looks like this:
<img width="1244" alt="screen shot 2017-08-14 at 4 15 21 pm" src="https://user-images.githubusercontent.com/5177299/29296373-b263ad6e-810e-11e7-8b21-d6520a962884.png">

**Comment by andrea-p** [comment]
@jfdesroches @worldsoup 

The tiles answer two different questions: (1) What functionality does Event Gateway have? (2) what does Event Gateway empower you to do?

So I think a better order is where we answer one question per line. Could optionally even bring that slash back and put answers to the second question below the slash. e.g.--

API gateway + pub/sub  |  Extendable through middleware  |  Platform agnostic
---slash---
Event Gateway is the backbone of serverless architectures.
Send events from any cloud  |  React to cross-cloud events  |  Expose events to your team

![image](https://user-images.githubusercontent.com/30416413/29341409-05b3076a-81d9-11e7-9bf8-84f962e97cdf.png)
