### ISSUE TITLE
Website rebrand: forms

### ISSUE THREAD

**Issue by jfdesroches** [serverless/site#132]
We have a few forms, I think it's worth detailing out how they work and where the data goes:

- [x] Join the Beta link: opens a popup, and the data should go into a table inside Airtable 

- [ ] Enterprise contact form: dumps into an _Enterprise_ table in Airtable CC @worldsoup for which one exactly

- [x] Newsletter sign up form: dumps into Mailchimp (like the one we use on the Blog sidebar). CC @DavidWells for help on this please :)

CC @steelbrain

**Comment by DavidWells** [comment]
Why do we want beta signups to go to airtable?

**Comment by worldsoup** [comment]
@DavidWells we're going offer a generic form so that we can get more information from them (role, use case, etc) and so that we can avoid the confusing double auth issue. We're going to be prompting everyone to login in order to use the gateway commands so there will be a lot more auth happening through the CLI.

**Comment by DavidWells** [comment]
Double auth issue is separate issue that needs to be addressed in product. (re only github on platform.com)

Adding people to a spreadsheet is a step backwards here & will cause a number of tracking headaches in the future.

Having a form with more fields (role, use case, etc) is achievable with auth0.

**Comment by worldsoup** [comment]
>Adding people to a spreadsheet is a step backwards here & will cause a number of tracking headaches in the future.

What exactly is the step backwards? I think we definitely want to watch the conversion rate...if this results in a lower signup rate then we can quickly switch back to auth0. It's possible it will result in a higher sign-up rate too.

**Comment by DavidWells** [comment]
AuthO is a database and single source of truth for users in the system.

- it handles data enrichment
- Single tracking IDs across all products.
- Connects with third party services (re forum user check / email flow
- It is searchable
- It means users don't need to recreate account for CLI/platform login
- It also means the user is cookied forever on their machine and we can identify repeat visitors etc.

It's a single sign on solution.

Air table is a online spreadsheet that is not wired into any of the aforementioned marketing pipeline. I added airtable to forms as a temporary hack to collect leads for entreprise page.

We can have web forms pass data into AuthO. I'm not sure why this is a problem here with continuing to do so. If we don't like the modal it has we can change that. If we want more fields on the form we can add them 

This is why putting data into a spreadsheet is a step backwards

**Comment by jfdesroches** [comment]
As long as the experience is like filling out a form (and not signing up with Github or whatever), I'm agnostic as to where the info goes.
