### ISSUE TITLE
Website rebrand: Company

### ISSUE THREAD

**Issue by jfdesroches** [serverless/site#138]
This is the "Meet the team" page that's currently on the .com site. 

We have some new images and blurbs to add for new teammates: [content and images Google Drive folder](https://drive.google.com/drive/folders/0B4DDXO5Kymj1YmJHbTk1VENPWjA)

**Comment by jfdesroches** [comment]
@DavidWells would you mind adding my ugly mug and blurb to the Team page please? Apparently I'm the holdout...

**Comment by DavidWells** [comment]
@jfdesroches done

**Comment by jfdesroches** [comment]
Thank you!
