### ISSUE TITLE
Search results vague. Hard to tell which provider.

### ISSUE THREAD

**Issue by rupakg** [serverless/site#152]
![image](https://user-images.githubusercontent.com/8188/29807726-337e29ec-8c63-11e7-9c87-b9e7132e30aa.png)

I think this is a regression.

**Comment by DavidWells** [comment]
Login docs are not prefixed 

Need the text in there https://github.com/serverless/serverless/blame/master/docs/providers/google/cli-reference/login.md#L13 for it to show up in search

**Comment by rupakg** [comment]
@DavidWells Assuming that the login is a generic command, do we have to duplicate the help text across all providers? Can we keep it at one place?

**Comment by DavidWells** [comment]
Most of these were updated by prefixing the page title with the provider like so https://github.com/serverless/serverless/blame/master/docs/providers/aws/guide/credentials.md#L13

If you see more, feel free to update them =)
