### ISSUE TITLE
Sticky Sidebar Overflowing Height

### ISSUE THREAD

**Issue by pelhage** [serverless/site#17]
If the sidebar contains many items, it will overflow into the footer as the user scrolls down and the sidebar reaches the footer.

![screenshot 2016-10-10 18 15 56](https://cloud.githubusercontent.com/assets/4411839/19255773/0dad1af2-8f16-11e6-9ec9-731f390f7efb.png)

**Comment by DavidWells** [comment]
Good eye! Fixed!
