### ISSUE TITLE
Sidebar obscures content when scrolling with a small window size

### ISSUE THREAD

**Issue by shanepelletier** [serverless/site#172]
This issue is probably best explained by a GIF:

![problem](https://user-images.githubusercontent.com/880164/30396885-7a1a7276-98a1-11e7-8cfa-ff990e272322.gif)

To reproduce: open a page on the docs (e.g. [this one](https://serverless.com/framework/docs/providers/aws/guide/functions/)) and resize your browser window to about half the screen (maybe smaller depending on your screen size).

Disabling uBlock doesn't solve the problem.

This issue is particularly troublesome when first starting to learn Serverless, since the Serverless browser window ends up almost crowding out anything else that I may have on my screen, e.g. a text editor, a console, etc.

OS: Windows 10
Browsers: Firefox 55.0.3 (64-bit), Google Chrome 60.0.3112.113

**Comment by DavidWells** [comment]
Thanks for the report and GIF! You da man

The problem is here: https://github.com/serverless/site/blob/master/src/layouts/Doc/index.js#L35

You can fix this by refreshing your browser in the tiny size. That will "fix" this for you until it's updated with a docs overhaul coming up.

**Comment by shanepelletier** [comment]
That "fix" does work although once I scroll all the way to the bottom it seems that the sidebar (bottom bar at this point) wants to "snap" into place. Feel free to close the issue if it's already on the backlog, I'm just leaving it open now to avoid closing + reopening in case it's a nice reminder for you guys.
