### ISSUE TITLE
https://serverless.com/blog/serverless-webtasks/ 404

### ISSUE THREAD

**Issue by gamebak** [serverless/site#183]
Hello,
Your latest article in the blog returns a 404 error.
https://serverless.com/blog/serverless-webtasks/

**Comment by DavidWells** [comment]
Is it still 404 for you?

Also, did you try refreshing the page when you saw the 404?

Thanks for the report

**Comment by gamebak** [comment]
Now it's working fine.
It didn't work when I went from the main page to the serverless webtasks blog post, I did attempt to reload and cleared the cache and it had that problem as well.

Not sure what was the issue, now it's working fine.

**Comment by DavidWells** [comment]
Cool thanks @gamebak =)
