### ISSUE TITLE
Blog: The "Next Page" button is not functioning properly

### ISSUE THREAD

**Issue by raeesbhatti** [serverless/site#198]
It keeps showing "Next Page" button at the bottom of Blog page even when there is no more content available for a new page. E.g. the "Next Page" button on this page shouldn't be there [Serverless Blog](https://59cf5efbdf99531c5ffb1d58--serverless.netlify.com/blog/page/5).

**Comment by DavidWells** [comment]
Thanks for the report. 

The next version of phenomic will solve this for us

Don't waste any time on this

**Comment by pdaryani** [comment]
Closing this since we've switched to Gatsby and this issue does not exist anymore
