### ISSUE TITLE
Link broken on the Serverless blog

### ISSUE THREAD

**Issue by solutionguy** [serverless/site#268]
Hi,

 Please can you fix this link?

https://serverless.com/blog/flask-python-rest-api-serverless-lambda-dynamodb/serverless.com/framework?rd=true

On this page.

https://serverless.com/blog/flask-python-rest-api-serverless-lambda-dynamodb/

Not sure if it should be a hyperlink at all?

**Comment by pdaryani** [comment]
Broken link was fixed
