### ISSUE TITLE
/event-gateway cleanup

### ISSUE THREAD

**Issue by worldsoup** [serverless/site#274]
- update top background image 
- remove gap above integrations graphic
![screen shot 2018-05-02 at 12 00 29 pm](https://user-images.githubusercontent.com/1475986/39543560-6edf0bb4-4e00-11e8-9211-930dc249b18d.png)
- remove red background to match style in sketch file of integrations graphic  
![screen shot 2018-05-02 at 12 00 47 pm](https://user-images.githubusercontent.com/1475986/39543589-882addd2-4e00-11e8-8798-2dc3fd3529cc.png)

**Comment by ac360** [comment]
Here is a version of the graphic with little whitespace around the edges:

![event-gateway-integrations-website](https://user-images.githubusercontent.com/2752551/39548047-a9993c94-4e59-11e8-910b-ebe1fba08296.png)

**Comment by pdaryani** [comment]
the new redesign includes fixes around spacing and an updated image for Event Gateway so closing this issue
