### ISSUE TITLE
broken 'github repo' button on https://serverless.com/framework/

### ISSUE THREAD

**Issue by dbrockus** [serverless/site#302]
Hello,  

The 'github repo' button on https://serverless.com/framework/ generates a 404.

I am running Firefox 61.01 on Ubuntu 18.04

David

![screenshot from 2018-07-26 17-03-36](https://user-images.githubusercontent.com/4910084/43291298-8b9658b4-90f6-11e8-8690-a1723be3aeb4.png)

**Comment by worldsoup** [comment]
thanks for pointing this out @dbrockus !! we'll get this fixed ASAP

**Comment by dbrockus** [comment]
Selecting the 'githug repo' button sends you to https://serverless.com/serverless/serverless?rd=true and generates a 404

![screenshot from 2018-07-26 17-13-10](https://user-images.githubusercontent.com/4910084/43291586-9e0cbd20-90f7-11e8-8c4b-c96d2c365886.png)

**Comment by dbrockus** [comment]
You are welcome @worldsoup.

**Comment by brianneisler** [comment]
This issue has been fixed.
