### ISSUE TITLE
broken link

### ISSUE THREAD

**Issue by WrathZA** [serverless/site#34]
Page: https://serverless.com/framework/docs/#contributing

_"Please read our **Contributing Document** to learn how you can start working on the Framework yourself."_

Contributing Document
- point to: https://serverless.com/framework/CONTRIBUTING
- instead of: https://github.com/serverless/serverless/blob/master/CONTRIBUTING.md

**Comment by DavidWells** [comment]
Thanks for the report. Really appreciate it!

The docs homepage just got all shifted around and this looks like it moved elsewhere.

😎
