### ISSUE TITLE
Table of Contents links don't work on variables page

### ISSUE THREAD

**Issue by alexdebrie** [serverless/site#345]
If I click the links near the top of the [Serverless Variables page](https://serverless.com/framework/docs/providers/aws/guide/variables/), it doesn't skip to the relevant section.

![links](https://user-images.githubusercontent.com/6509926/46628364-eeb4ce80-cb02-11e8-8d89-ed3b164d5f7b.gif)

**Comment by pdaryani** [comment]
Hi @alexdebrie, this issue has now been fixed: https://serverless.com/framework/docs/providers/aws/guide/variables/
