### ISSUE TITLE
Web api link broken

### ISSUE THREAD

**Issue by jarrettj** [serverless/site#36]
Link to 
https://serverless.com/framework/docs/providers/aws/examples/web-api/https://serverless.com/framework/docs/providers/aws/examples/web-api does not work.

**Comment by DavidWells** [comment]
@jarrettj where did you see think link?

**Comment by jarrettj** [comment]
Goto https://serverless.com/framework/docs/providers/aws

The web-api link under examples section.

**Comment by DavidWells** [comment]
Thanks for the report. Checkout https://github.com/pmuens/serverless-crud for a CRUD webapi example.

We will be re-adding this to our docs shortly

**Comment by jarrettj** [comment]
Cool man!
