### ISSUE TITLE
Walkthroughs have no links

### ISSUE THREAD

**Issue by dandv** [serverless/site#375]
How can I check the walkthroughs? Clicking on them in Chrome does nothing.

![image](https://user-images.githubusercontent.com/33569/48101120-d0fa8800-e1da-11e8-8e42-fa443eb93317.png)

**Comment by worldsoup** [comment]
hey @dandv thanks for the issue, which page are you seeing this on?

**Comment by dandv** [comment]
https://serverless.com/learn/use-cases/
