### ISSUE TITLE
Links in paragraphs cannot be clicked if they precede an h2/h3 with an id attribute

### ISSUE THREAD

**Issue by crgeary** [serverless/site#405]
The documentation site has a rule that sets a negative `margin-top` of `-60px` to all headings that have an `id=""` attribute. Presumably this has something to do with the sticky header.

Because of this, it's not possible to click any links that are in the last 2 lines of the previous paragraph because they're sitting behind the headings. In this particular example, when trying to click on the "a fix is in the works" link, it's actually clicking on the `<h2>` element and therefore the link does not work.

Here is the page where I noticed the error: 
https://serverless.com/framework/docs/providers/aws/guide/services/#creation

![image](https://user-images.githubusercontent.com/3949335/49687951-a87beb80-fb02-11e8-949d-f050c49785c0.png)

Tested on latest Chrome & Firefox on Mac Mojave.

**Comment by pdaryani** [comment]
Thanks @crgeary, this issue has been resolved via the following PR: https://github.com/serverless/site/pull/406 

A hacky fix for now but I'm working on a front-end overhaul for the docs section so will implement the proper solution then :)
