### ISSUE TITLE
Serverless font/typeface

### ISSUE THREAD

**Issue by rootbeersoup** [serverless/site#414]
I really like the font used on the website for the logo, links, etc. It looks like a custom font since I couldn't find it anywhere else. I was wondering if it's ok to use the font for one of my personal projects? I see the repo is licensed under the MIT license and the otf file is hosted here, but I'm not exactly sure how font files fall under open source licenses, so I figured I'd ask here for permission just to be safe.

Thanks.

**Comment by pdaryani** [comment]
Hey @rootbeersoup, really sorry for taking forever to get back to you on this. Not sure if it still applies but, of course, feel free to use the font and if you could give Serverless credit for it in the footer, that'll be awesome!
