### ISSUE TITLE
Link to 'AWS system credentials' is broken, 404

### ISSUE THREAD

**Issue by pal** [serverless/site#42]
When following the first step in the guide (at https://serverless.com/framework/docs/providers/aws/guide/), the first link to click is https://serverless.com/framework/docs/providers/aws/guide/guide/credentials/ and when doing that, I'm immediately greeted by a 404.

The correct link seems to be https://serverless.com/framework/docs/providers/aws/guide/credentials/ (you stuck an extra /guide/ in there)

**Comment by DavidWells** [comment]
fixed!
