### ISSUE TITLE
Improve docs hyperlink style

### ISSUE THREAD

**Issue by jonatasbaldin** [serverless/site#445]
# Docs Hyperlink Style

## Description
The docs hyperlink style is quite misleading, since you need to hover the cursor on the word to see that it is actually a link.

As an example, the first paragraph os [AWS - Resources](https://serverless.com/framework/docs/providers/aws/guide/resources/):
![image](https://user-images.githubusercontent.com/8570364/56669045-d4ae9800-66b0-11e9-852b-5a4417c1d844.png)

The are two clickable links in this paragraph, but it's hard to identify. The italic doesn't give a clear clue. It would be nicer with underlines:
![image](https://user-images.githubusercontent.com/8570364/56669198-10e1f880-66b1-11e9-9ddd-28203dd8eb0d.png)

What do you think?

Cheers!

**Comment by pdaryani** [comment]
Thanks @jonatasbaldin, totally agree! right now links don't actually look like links :)

On that note, I'm working on revamping the entire docs frontend, here's a preview of what the section would look like:
![new-docs-frontend](https://user-images.githubusercontent.com/43791027/56846529-ad361600-68d0-11e9-9e34-23f16417acdd.png)

the link bit is much clearer etc

Would be great to get your feedback on this

Cheers

**Comment by jonatasbaldin** [comment]
That looks quite cool, congrats :)

IMHO, the AWS header image looks a bit off, I'd go with a transparent background and a color AWS logo, maybe?

Cheers mate!

**Comment by pdaryani** [comment]
Thanks, good feedback regarding the AWS logo bit :)

Also, side note: links actually looking like links fix is already live: https://serverless.com/framework/docs/providers/aws/

and a proper frontend revamp for docs coming up next

**Comment by jonatasbaldin** [comment]
Nice, thanks!
