### ISSUE TITLE
Broken links list

### ISSUE THREAD

**Issue by Devinsuit** [serverless/site#54]
- [x] https://serverless.com/framework/docs/ - [Cron](https://serverless.com/framework/docs/providers/aws/examples/cron)
- [x] https://serverless.com/framework/docs/ - [Web Serving HTML](https://serverless.com/framework/docs/providers/aws/examples/web-serving-html). Issue https://github.com/serverless/site/issues/53 and https://github.com/serverless/site/issues/46
- [x] https://serverless.com/framework/docs/providers/aws/guide/ - [    AWS system credentials](https://serverless.com/framework/docs/providers/aws/guide/guide/credentials/). Issue https://github.com/serverless/site/issues/42
- [x] https://serverless.com/framework/docs/providers/aws/cli-reference/ - [AWS system credentials](https://serverless.com/framework/docs/providers/aws/cli-reference/guide/credentials/)
- [x] https://serverless.com/framework/docs/providers/aws/events/ - [   AWS system credentials](https://serverless.com/framework/docs/providers/aws/events/guide/credentials/)
- [x] https://serverless.com/learn/graphql-and-serverless/ - [Medium](https://serverless.com/learn/graphql-and-serverless/www.medium.com)
- [x] https://serverless.com/learn/graphql-and-serverless/ - [HearthPwn](https://serverless.com/learn/graphql-and-serverless/www.hearthpwn.com)
- [x] https://serverless.com/learn/graphql-and-serverless/ - [  Mobafire](https://serverless.com/learn/graphql-and-serverless/www.mobafire.com)
- [x] https://serverless.com/blog/serverless-v1-0-beta-release-1/ - [   The documentation](http://v1.docs.serverless.com/)
- [x] https://serverless.com/blog/building-a-serverless-screenshot-service-with-lambda/ - [email](https://serverless.com/blog/building-a-serverless-screenshot-service-with-lambda/mail@svdgraaf.nl)
- [x] https://serverless.com/framework/docs/providers/aws/guide/credentials/ - [variables](https://serverless.com/framework/docs/providers/aws/guide/serverless-variables)
- [x] https://serverless.com/framework/docs/providers/aws/guide/services/ - [deployment guide](https://serverless.com/framework/docs/providers/aws/guide/deployment)
- [x] https://serverless.com/framework/docs/providers/aws/guide/v0_to_v1/ - [   serverless.yml file](https://serverless.com/framework/docs/providers/aws/guide/guide/serverless-yml-reference)
- [x] https://serverless.com/framework/docs/providers/aws/guide/v0_to_v1/ - [   change the packaging behavior](https://serverless.com/framework/docs/providers/aws/guide/guide/packaging)
- [x] https://serverless.com/framework/docs/providers/aws/guide/v0_to_v1/ - [our guide](https://serverless.com/framework/docs/providers/aws/guide/guide/custom-provider-resources)
- [x] https://serverless.com/framework/docs/providers/aws/guide/v0_to_v1/ - [   extending serverless docs](https://serverless.com/framework/docs/providers/aws/guide/extending-serverless)
- [x] https://serverless.com/framework/docs/providers/aws/guide/v0_to_v1/ - [   APIG integration in our event docs](https://serverless.com/framework/docs/providers/aws/guide/providers/aws/events/apigateway)
- [x] https://serverless.com/framework/docs/providers/aws/guide/v0_to_v1/ - [   AWS provider documentation](https://serverless.com/framework/docs/providers/aws/guide/providers/aws)
- [x] https://serverless.com/framework/docs/providers/aws/guide/v0_to_v1/ - [our guide](https://serverless.com/framework/docs/providers/aws/guide/guide)
- [ ] https://serverless.com/blog/serverless-v1-0-alpha-release-2/ - [  first release](https://serverless.com/blog/serverless-v1-0-alpha1-announcement/)
- [ ] https://serverless.com/blog/serverless-v1-0-alpha-release-2/ - [  here](https://serverless.com/blog/building-serverless-framework-v1/)
- [ ] https://serverless.com/framework/docs/providers/aws/guide/deploying/ - []()

**Comment by Aron3d** [comment]
Add:
https://serverless.com/framework/docs/providers/aws/guide/events/

**Comment by DavidWells** [comment]
@Devinsuit you are my hero! Do you have a tool for checking 404s or was this done by hand?

Many many many thanks!

**Comment by Devinsuit** [comment]
@DavidWells  I have a tool. You're welcome!

**Comment by DavidWells** [comment]
@Devinsuit what tool are you using? =)
