### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by jamesjryan** [serverless/site#61]
Broken link at https://serverless.com/framework/docs/providers/aws/events/apigateway/

Followed on left sidebar from https://serverless.com/framework/docs/providers/aws/events/

**Comment by DavidWells** [comment]
Hey James thanks for the report.

I am seeing: https://serverless.com/framework/docs/providers/aws/events/apigateway/ 

Are you still not?

**Comment by jamesjryan** [comment]
Wow, weird, I'm seeing it fine now. Close the issue :)

**Comment by DavidWells** [comment]
:)
