### ISSUE TITLE
Add z-index for algolia search / suggestions popup in docs

### ISSUE THREAD

**Issue by pmuens** [serverless/site#62]
The suggestion popup is currently a little bit broken. Maybe adding a `z-index` helps here:

![bildschirmfoto 2016-11-17 um 15 17 53](https://cloud.githubusercontent.com/assets/1606004/20395424/25a8d8d6-ace3-11e6-94f6-7610cb94813e.png)

**Comment by DavidWells** [comment]
good eye sniper! Fixed this and made the search box a lil bit wider

**Comment by pmuens** [comment]
Awesome! You rock @DavidWells 🎉
