### ISSUE TITLE
Add right margin for resource logical id table

### ISSUE THREAD

**Issue by pmuens** [serverless/site#65]
The reference table for resource logical ids has no right margin / padding. This way it looks like one needs to scroll to the right side to see all the table content.

Some space at the right might improve the overall look and feel.

![bildschirmfoto 2016-11-24 um 13 48 52](https://cloud.githubusercontent.com/assets/1606004/20600182/98f2c648-b252-11e6-90b7-ff469f9fb11a.png)

**Comment by pdaryani** [comment]
closing since this issue relates to the older version of our website
