### ISSUE TITLE
Underline all words when hovering over link

### ISSUE THREAD

**Issue by pmuens** [serverless/site#66]
If one hovers over the last word (e.g. after a line break) only this word gets underlined in a dark black although both words make up the link.

I added a screenshot where I hovered over `Stats` of the `Serverless Stats` link. You can see that only `Stats` is underlined in dark black.

![bildschirmfoto 2016-11-24 um 14 26 35](https://cloud.githubusercontent.com/assets/1606004/20600247/f15dbebe-b252-11e6-908e-8b8982458640.png)

**Comment by DavidWells** [comment]
I think this was fixed. Closing!

**Comment by pmuens** [comment]
Yep. That seems to be fixed.

Thanks 👍
