### ISSUE TITLE
Copy link to clipboard not working with Safari

### ISSUE THREAD

**Issue by pmuens** [serverless/site#72]
The copy to clipboard functionality does not work with Safari.

Here's the code which implements this functionality:
https://github.com/serverless/site/blob/master/src/components/Copy

Using this library might help here as it should work cross browser: https://github.com/zenorocha/clipboard.js

**Comment by DavidWells** [comment]
@pmuens you mean this lib https://github.com/serverless/site/blob/master/package.json#L120 =)

Not sure why it's not working on safari

What version is your safari? https://github.com/zenorocha/clipboard.js#browser-support

**Comment by pmuens** [comment]
@DavidWells whoops. I missed that whole digging through the code...

I have this Safari version installed:

```
Version 10.0.1 (12602.2.14.0.7)
```

**Comment by DavidWells** [comment]
The clipboard package doesn't work in safari. ¯\_(ツ)_/¯

Might add in `zero-clipboard` but wanted to avoid site bloat

**Comment by pmuens** [comment]
No worries I use chrome most of the time. Not sure what the current browser stats are on our site...

+1 for not adding that much site bloat.
