### ISSUE TITLE
Broken link - https://serverless.com/framework/docs/providers/aws/cli-reference/config

### ISSUE THREAD

**Issue by mkjsix** [serverless/site#73]
From page https://serverless.com/framework/docs/providers/aws/guide/credentials/ the link on below sentence gives a 404 not found:

> Take a look at the [config CLI reference](https://serverless.com/framework/docs/providers/aws/cli-reference/config) for more information about credential configuration.

**Comment by dev-fullstacktechnology** [comment]
I tried to access same page from aws config
serverless config credentials --provider aws --key key --secret secret
and config command also show not found...please help...

**Comment by DavidWells** [comment]
https://serverless.com/framework/docs/providers/aws/cli-reference/config-credentials/
