### ISSUE TITLE
Community link in the mobile navbar not working

### ISSUE THREAD

**Issue by nielslanting** [serverless/site#76]
**Issue:**
The Community link in the mobile navbar is not working on mobile chrome.

In the file: site/src/fragments/Header/index.js

`<span href='http://forum.serverless.com/' target='_blank' className={styles.link}>
                    Community <svg className={styles.caret} width='8' height='4' viewBox='62 7 10 6'><path d='M71.884 7.698l-4.56 5.116c-.013.022-.008.05-.026.07-.083.084-.192.12-.3.116-.106.004-.214-.033-.295-.117-.02-.02-.014-.047-.028-.068L62.115 7.7c-.154-.16-.154-.42 0-.58.156-.16.408-.16.563 0L67 11.97l4.322-4.85c.155-.16.406-.16.56 0 .157.16.157.418.002.578z' fill='#fff' /></svg>
                  </span>`

`span > href` doesn't seem to work on mobile chrome.

**Comment by DavidWells** [comment]
Updated the mobile nav. Thanks for the heads up!
