### ISSUE TITLE
Clean up imports

### ISSUE THREAD

**Issue by nikgraf** [serverless/site#8]
Current structure:

```js
Button/Button.js
Button/Button.css
```

which leads to these imports:
`import Button from './components/Button/Button'`

-----------

What about we change the structure of components to e.g.

```js
Button/index.js
Button/Button.css
```

or even

```js
Button/index.js
Button/styles.css
```

This makes the imports way cleaner: `import Button from './components/Button'`

**Comment by nikgraf** [comment]
btw I'm happy to make a PR in case you agree

**Comment by DavidWells** [comment]
Yeah I'm going to clean it up.

Button.js
Button.css
Index.js for easy exports

**Comment by nikgraf** [comment]
why keep Button.js anyway? From my experience it's just more of a hassle when you rename components.

Is there a benefit I might have missed? 😄

**Comment by DavidWells** [comment]
I updated this on my end.

The component file names make them easier to jump to in an IDE.

![image](https://cloud.githubusercontent.com/assets/532272/18383917/1497d59c-7688-11e6-97b7-3ce3d241a9f1.png)

**Comment by nikgraf** [comment]
If you have only the index.js it will still be the first result if you type `but`

**Comment by DavidWells** [comment]
@nikgraf good point =P I will think about changing.

I also like seeing the filename in my IDE but there are ways I can probably fix this too.

I've added index files for now. 

I'd love to pair with you on some stuff when you get into town next week!
