### ISSUE TITLE
SyntaxError: Block-scoped declarations

### ISSUE THREAD

**Issue by iamShantanu101** [serverless/site#81]
Getting the following error block while doing npm start.
`  let fixedContent = content.replace(/([0-9]{2})-/g, '').replace(/.md\)/g, ')')
  ^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/shantanudeshpande/site/scripts/docs/index.js:9:28)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)

npm ERR! Darwin 16.3.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "prepareContent"
npm ERR! node v4.6.0
npm ERR! npm  v4.1.1
npm ERR! code ELIFECYCLE
npm ERR! serverless-site@0.0.1 prepareContent: `node scripts/docs && node scripts/blog`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the serverless-site@0.0.1 prepareContent script 'node scripts/docs && node scripts/blog'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the serverless-site package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/docs && node scripts/blog
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs serverless-site
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls serverless-site
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/shantanudeshpande/site/npm-debug.log

npm ERR! Darwin 16.3.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run-script" "dev"
npm ERR! node v4.6.0
npm ERR! npm  v4.1.1
npm ERR! code ELIFECYCLE
npm ERR! serverless-site@0.0.1 dev: `npm run prepareContent && phenomic start`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the serverless-site@0.0.1 dev script 'npm run prepareContent && phenomic start'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the serverless-site package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run prepareContent && phenomic start
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs serverless-site
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls serverless-site
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/shantanudeshpande/site/npm-debug.log
ERROR: dev: None-Zero Exit(1);

npm ERR! Darwin 16.3.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v4.6.0
npm ERR! npm  v4.1.1
npm ERR! code ELIFECYCLE
npm ERR! serverless-site@0.0.1 start: `npm-run-all --parallel dev watch`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the serverless-site@0.0.1 start script 'npm-run-all --parallel dev watch'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the serverless-site package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm-run-all --parallel dev watch
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs serverless-site
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls serverless-site
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/shantanudeshpande/site/npm-debug.log`

**Comment by DavidWells** [comment]
What version of node are you running?

You might need to update to v 6+

**Comment by iamShantanu101** [comment]
Solved! Updated node to latest version and it worked.
