### ISSUE TITLE
Blog link without trailing / returns 404

### ISSUE THREAD

**Issue by pmuens** [serverless/site#82]
Just stumbled upon this one today.

Blog links without a trailing `/` return a 404 whereas their corresponding equivalent with a trailing `/` are fine:

Fine: --> https://serverless.com/blog/scope-the-open-source-serverless-status-board/
404: --> https://serverless.com/blog/scope-the-open-source-serverless-status-board

Seems to be a problem related to the blog since other links such as

https://serverless.com/framework/docs/providers/aws/guide/installation

or 

https://serverless.com/framework

work fine...

**Comment by DavidWells** [comment]
Seems fixed

**Comment by pmuens** [comment]
Yes, working fine now! 👍
