### ISSUE TITLE
https://serverless.com/framework/docs/providers/aws/vpc/

### ISSUE THREAD

**Issue by adityap86** [serverless/site#88]
This page is broken

**Comment by DavidWells** [comment]
Hey @adityap86 

Where did you find a link to this page?

Thanks

**Comment by adityap86** [comment]
Hey @DavidWells 

Found it on the forum (http://forum.serverless.com/t/connect-to-mysql/521), Check out the 2 comment from top by flomotlik. He has referred the link. Currently i am trying to connect to a database in a VPC which is located in a different region.

**Comment by pdaryani** [comment]
Content from https://serverless.com/framework/docs/providers/aws/vpc/ 
has been migrated to 
https://serverless.com/framework/docs/providers/aws/guide/functions/#vpc-configuration

Above given, I've added a 301 redirect from /aws/vpc to /guide/functions
