### ISSUE TITLE
Starting Commands Are out of Date

### ISSUE THREAD

**Issue by danielrasmuson** [serverless/site#9]
The documentation for the starting command, seem to be out of date.

Specifically..
```
serverless create
serverless deploy
```

Should it be "serverless project create?"

https://serverless.com/
https://github.com/serverless/site/blob/731545151ca72224636c4c771a3ec23500a261e6/src/pages/Homepage/terminalCommands.js

**Comment by DavidWells** [comment]
@danielrasmuson thanks for the report.

sls project create was for version 0.x

The new command is `serverless create` in version 1+
