### ISSUE TITLE
Doc for google cloud functions is missing

### ISSUE THREAD

**Issue by murali129** [serverless/site#95]
The link for docs for deploying google cloud functions using serverless is missing from serverless website and here I have attached the link for website [web link](https://serverless.com/framework/docs/providers/google/guide/intro/)

**Comment by afeld** [comment]
Similarly, [the homepage](https://serverless.com/) still says

> Build auto-scaling, pay-per-execution, event-driven apps on AWS Lambda

while [the repository](https://github.com/serverless/serverless) says

> serverless architectures using AWS Lambda, Azure Functions, Google CloudFunctions & more!

Would be great to have this consistent!

**Comment by worldsoup** [comment]
@murali129 the GCF plugin is still in beta, we're planning a public release in a couple weeks at which point we'll include the docs on the site, thanks for noticing though!
