### ISSUE TITLE
npm install and start is throwing an error

### ISSUE THREAD

**Issue by mmchougule** [serverless/site#99]
I am very new to serverless. I am just trying to get serverles/site example on my local machine. As mentioned in the quickstart guide, I cloned the git repository, did npm install and it is throwing an error while cloning into 'serverless' -> Permission denied (publickey). "Please make sure you have the correct access rights and the repository exists."

Also when I try to run it using npm start, it throws this error:

npm ERR! serverless-site@0.0.1 start: `npm-run-all --parallel dev watch`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the serverless-site@0.0.1 start script 'npm-run-all --parallel dev watch'.

Can anyone please help me understand how to fix this issue?

I just wanted to see how it works and if I can run the serverless site example on my local.

I have the latest node v 7.8.0 and npm v 4.2.0 installed. I would appreciate any help.

**Comment by DavidWells** [comment]
`git clone git@github.com:serverless/serverless.git`

and 

`git clone git@github.com:serverless/serverless.git serverless-blog`

in the root directory of the site. You are missing the additional markdown files for the site to build.

The site directory should look like: 
![image](https://cloud.githubusercontent.com/assets/532272/24592155/f3d0b156-17ce-11e7-91d9-261de5f800ae.png)

**Comment by mmchougule** [comment]
Thank you @DavidWells 

I did git clone for those two repositories. Now my directory looks like this:

<img width="826" alt="screen shot 2017-04-02 at 8 21 00 pm" src="https://cloud.githubusercontent.com/assets/18723323/24592299/f2c01d0c-17e1-11e7-9541-302c93c1bc23.png">


When I do "npm start", I get the following message:

npm ERR! serverless-site@0.0.1 start: `npm-run-all --parallel dev watch`
npm ERR! Exit status 1

Also attaching the log I see on my terminal and the log I found on npm logs.  Am I doing something wrong?
[2017-04-03T00_21_55_523Z-debug.log.zip](https://github.com/serverless/site/files/888772/2017-04-03T00_21_55_523Z-debug.log.zip)
[npm-start-output.txt](https://github.com/serverless/site/files/888773/npm-start-output.txt)

**Comment by DavidWells** [comment]
```
Error: ENOENT: no such file or directory, stat '/Users/mayur/Documents/projects/site/serverless-blog/posts'
```

What is inside your `serverless-blog` directory?

**Comment by mmchougule** [comment]
I don't have that directory. Is this where I get it from ?
https://github.com/serverless/blog/tree/master/posts

**Comment by DavidWells** [comment]
Oops. Clone the blog into `serverless-blog`

`git clone git@github.com:serverless/blog.git serverless-blog`

**Comment by mmchougule** [comment]
Ha, thank you so much @DavidWells 

It works now! :)

**Comment by DavidWells** [comment]
Cool! Let me know if you have any other questions =)

I have a simpler setup for my personal site over here: https://github.com/DavidWells/davidwells.io (this one only uses a single repo for the content)

**Comment by DavidWells** [comment]
Also see https://phenomic.io for docs on how the site/phenomic work

They also have a base starter theme

To use serverless, install our CLI `npm I serverless -g` :)

**Comment by mmchougule** [comment]
Awesome, you are the best! I will check out your site as well. I did install serverless. I shall deploy a sample application soon.
Thank you for your help!
